---
plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

# Filtros básicos apenas
filters:
  instance-state-name: running

# Organização por tags
keyed_groups:
  # Grupo por Tier
  - key: tags.Tier
    prefix: tier
    separator: "_"

  # Grupo por Role
  - key: tags.Role
    prefix: role
    separator: "_"

  # Grupo por Environment
  - key: tags.Environment
    prefix: env
    separator: "_"

# Configurações de conexão
compose:
  ansible_host: private_ip_address
  ansible_user: ubuntu
  ansible_ssh_private_key_file: ~/.ssh/id_rsa
  ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10
  ansible_python_interpreter: /usr/bin/python3

# Naming das instâncias
hostnames:
  - tag:Name
  - instance-id