---
- name: Provisionar EC2 com Nginx
  hosts: all
  become: true
  vars:
    ansible_ssh_private_key_file: /mnt/c/Users/Lesley/Documents/Curso-gabriel/AWS-Keys/key/aws-key.pem
    ansible_user: ubuntu

  tasks:
    - name: Atualizar pacotes
      apt:
        update_cache: yes

    - name: Instalar Nginx
      apt:
        name: nginx
        state: present

    - name: Copiar index.html
      copy:
        src: /mnt/c/Users/Lesley/Documents/Curso-gabriel/Terraform/projeto-devops/Ansible/index.html
        dest: /var/www/html/index.html
        mode: '0644'
